// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6w4-ffAgCNTBKXuusUBOTtlrWkdcfXyY',
    appId: '1:355936712147:web:bbb29e8b873cad3692ab26',
    messagingSenderId: '355936712147',
    projectId: 'journal-2b797',
    authDomain: 'journal-2b797.firebaseapp.com',
    storageBucket: 'journal-2b797.appspot.com',
    measurementId: 'G-HCVV4FKBNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgF04TWoUZLo-L4vJYNtAlct3qhLSVq6Y',
    appId: '1:355936712147:android:78676c4c723c1ff492ab26',
    messagingSenderId: '355936712147',
    projectId: 'journal-2b797',
    storageBucket: 'journal-2b797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ962Yfv9up3VOfKsUeS1_cY_ijBJ504g',
    appId: '1:355936712147:ios:59e9bc63a227cafe92ab26',
    messagingSenderId: '355936712147',
    projectId: 'journal-2b797',
    storageBucket: 'journal-2b797.appspot.com',
    iosClientId: '355936712147-0kn3u2kgm1cpnicna364jlpgfv34mqpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ962Yfv9up3VOfKsUeS1_cY_ijBJ504g',
    appId: '1:355936712147:ios:e84eb89f5a0bce4c92ab26',
    messagingSenderId: '355936712147',
    projectId: 'journal-2b797',
    storageBucket: 'journal-2b797.appspot.com',
    iosClientId: '355936712147-6fjsdhrccfjb9uai75nr7vdervl64nrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.journal.RunnerTests',
  );
}
